[package]
name = "inkwell_test"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.68"


